version: '3'

services: 
  react:
    build:
      context: .
      dockerfile: ./compose/local/react/Dockerfile
    volumes:
      - ./front:/home/app/react
    env_file:
      - ./compose/docker_env/local/react.env
    network_mode: host
    stdin_open: true
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - db
    env_file:
      - ./compose/docker_env/local/django.env
    volumes:
      - ./back:/home/app/web
      - eq_static_volume:/home/app/static
      - eq_media_volume:/home/app/media
    ports:
      - "9000:9000"
    stdin_open: true
  db:
    image: "postgres:13.4-alpine"
    build:
      context: .
      dockerfile: ./compose/local/db/Dockerfile
    env_file:
      - ./compose/docker_env/local/db.env
    stdin_open: true
    ports:
      - "9001:5432"
    volumes:
      - eq_postgres_volume:/var/lib/mysql
      - ./db/scripts:/home/app/scripts
  nginx:    
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    ports:
      - 9002:80
    volumes:
      - eq_static_volume:/home/app/static
      - eq_media_volume:/home/app/media
    depends_on:
      - django

volumes:
  eq_postgres_volume:
  eq_static_volume:
  eq_media_volume: