version: "3"

services:
  django:
    restart: always
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL
      - SECRET_KEY=0c63a75b845e4f7d01107d852e4c2485c51a50aaaa94fc61995e71bbee983a2ac3713831264adb47fb6bd1e058d5f004
      - PG_DB_NAME=db_develop
      - PG_USER=eq_production
      - PG_PASS=IgAM@VLzfKO#
      - PG_HOST=db
      - PG_PORT=5432
      - ALLOWED_HOSTS=*, 127.0.0.1, localhost
      - SECURE_HSTS_SECONDS=15
      - SECURE_HSTS_INCLUDE_SUBDOMAINS=True
      - SECURE_SSL_REDIRECT=False
      - CSRF_COOKIE_SECURE=True
      - SESSION_COOKIE_SECURE=True
      - SECURE_HSTS_PRELOAD=True
      - DJANGO_SETTINGS_MODULE=src.settings.production
      - RUNSERVER_PORT=9000
      - RUNSERVER_ADDR=0.0.0.0
    volumes:
      - eq_static_volume:/home/app/static
      - eq_media_volume:/home/app/media
    stdin_open: true
  db:
    restart: always
    image: "postgres:13.4-alpine"
    environment:
      - POSTGRES_DB=db_develop
      - POSTGRES_USER=eq_production
      - POSTGRES_PASSWORD=IgAM@VLzfKO#
    stdin_open: true
    volumes:
      - eq_postgres_volume:/var/lib/mysql
  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./compose/production/nginx/letsencrypt:/etc/letsencrypt
      - eq_static_volume:/home/app/static
      - eq_media_volume:/home/app/media
    depends_on:
      - django
volumes:
  eq_postgres_volume:
  eq_static_volume:
  eq_media_volume:
